// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ES9jzjLPuOxdzJN1zj_I5wngPPTw2c4',
    appId: '1:429121934475:web:60fdf594c9f8ce8053308e',
    messagingSenderId: '429121934475',
    projectId: 'sangam-exp-inv-2026',
    authDomain: 'sangam-exp-inv-2026.firebaseapp.com',
    storageBucket: 'sangam-exp-inv-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATdrlmG4-Sf9xiMDGU_ICoFEeziarizaM',
    appId: '1:429121934475:ios:230c1dc87a8249f853308e',
    messagingSenderId: '429121934475',
    projectId: 'sangam-exp-inv-2026',
    storageBucket: 'sangam-exp-inv-2026.firebasestorage.app',
    iosBundleId: 'com.makeinsatara.sangam',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBro66pMEslujNlkYEZBf_P57ePSxm_DbU',
    appId: '1:429121934475:android:9ac8251577ca4e4153308e',
    messagingSenderId: '429121934475',
    projectId: 'sangam-exp-inv-2026',
    storageBucket: 'sangam-exp-inv-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4ES9jzjLPuOxdzJN1zj_I5wngPPTw2c4',
    appId: '1:429121934475:web:8f627e9592fc6fea53308e',
    messagingSenderId: '429121934475',
    projectId: 'sangam-exp-inv-2026',
    authDomain: 'sangam-exp-inv-2026.firebaseapp.com',
    storageBucket: 'sangam-exp-inv-2026.firebasestorage.app',
  );

}